# --- Global Hardware Definitions ---
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=3
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=3
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n
CONFIG_ZMK_IDLE_TIMEOUT=150000
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
CONFIG_ZMK_EXT_POWER=y
CONFIG_ZMK_USB=y
CONFIG_BT_BUF_ACL_RX_SIZE=512
CONFIG_BT_CTLR_DATA_LENGTH_MAX=251
CONFIG_ZMK_USB_LOGGING=n
CONFIG_ZMK_BLE_CLEAR_BONDS_ON_START=n

# --- Dummy Hardware Support ---
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=0
CONFIG_ZMK_RGB_UNDERGLOW_BRT_MAX=30
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y

# --- OLED Display Settings ---
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y

# --- Left WPM Widgets (Graph Setup) ---
CONFIG_ZMK_WPM=y

# 1. Disable the defaults you don't want
CONFIG_NICE_OLED_WIDGET_WPM_NUMBER=n
CONFIG_NICE_OLED_WIDGET_WPM_SPEEDOMETER=n

# 2. Enable the Graph
CONFIG_NICE_OLED_WIDGET_WPM_GRAPH=y
CONFIG_NICE_OLED_WIDGET_WPM_GRAPH_FIXED_RANGE=y
CONFIG_NICE_OLED_WIDGET_WPM_GRAPH_FIXED_RANGE_MAX=100

# 3. Keep Luna if you want her on top of the graph
CONFIG_NICE_OLED_WIDGET_WPM_LUNA=y

# --- Studio ---
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=n
