# Central-only USB and Logging
CONFIG_ZMK_USB=y
CONFIG_ZMK_USB_LOGGING=n

# Words Per Minute Tracker
CONFIG_ZMK_WPM=y

# Luna Modifiers Widget
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS_LUNA=y

# HID Indicators (Caps Lock Alert)
CONFIG_NICE_OLED_WIDGET_HID_INDICATORS=y
CONFIG_NICE_OLED_WIDGET_HID_INDICATORS_LUNA=y
CONFIG_NICE_OLED_WIDGET_HID_INDICATORS_LUNA_ONLY_CAPSLOCK=y

# FIX: Force the OLED module to render these instead of defaults
CONFIG_NICE_OLED_WIDGET_HID_INDICATORS_STATUS_SCREEN_ONLY=y

# ZMK Studio
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=n
