# Peripheral (Right Side) Animation
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL=y
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_SPACEMAN=y

# FIX: Force the OLED module to prioritize this animation
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_STATUS_SCREEN_ONLY=y
